# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eshipping.proto"\x16\n\x14ServiceStatusRequest".\n\x12ServiceStatusReply\x12\x10\n\x03\x65rr\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_err"`\n\x14ShippingOrderRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x02\x12\x10\n\x08order_id\x18\x04 \x01(\t"X\n\x12ShippingOrderReply\x12\x10\n\x03\x65rr\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0btracking_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_errB\x0e\n\x0c_tracking_id"\x7f\n\rShippingOrder\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x02\x12\x10\n\x08order_id\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x61te_created\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t"*\n\x13\x46indShippingRequest\x12\x13\n\x0btracking_id\x18\x01 \x01(\t"m\n\x11\x46indShippingReply\x12\x10\n\x03\x65rr\x18\x01 \x01(\tH\x00\x88\x01\x01\x12+\n\x0eshipping_order\x18\x02 \x01(\x0b\x32\x0e.ShippingOrderH\x01\x88\x01\x01\x42\x06\n\x04_errB\x11\n\x0f_shipping_order"\x17\n\x15GetAllShippingRequest"X\n\x13GetAllShippingReply\x12\x10\n\x03\x65rr\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\'\n\x0fshipping_orders\x18\x02 \x03(\x0b\x32\x0e.ShippingOrderB\x06\n\x04_err2\x8d\x02\n\x0fShippingService\x12=\n\rServiceStatus\x12\x15.ServiceStatusRequest\x1a\x13.ServiceStatusReply"\x00\x12=\n\rShippingOrder\x12\x15.ShippingOrderRequest\x1a\x13.ShippingOrderReply"\x00\x12:\n\x0c\x46indShipping\x12\x14.FindShippingRequest\x1a\x12.FindShippingReply"\x00\x12@\n\x0eGetAllShipping\x12\x16.GetAllShippingRequest\x1a\x14.GetAllShippingReply"\x00\x42=Z;github.com/farhanangullia/ecommerce-app/shipping-service/pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "shipping_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z;github.com/farhanangullia/ecommerce-app/shipping-service/pb"
    )
    _globals["_SERVICESTATUSREQUEST"]._serialized_start = 18
    _globals["_SERVICESTATUSREQUEST"]._serialized_end = 40
    _globals["_SERVICESTATUSREPLY"]._serialized_start = 42
    _globals["_SERVICESTATUSREPLY"]._serialized_end = 88
    _globals["_SHIPPINGORDERREQUEST"]._serialized_start = 90
    _globals["_SHIPPINGORDERREQUEST"]._serialized_end = 186
    _globals["_SHIPPINGORDERREPLY"]._serialized_start = 188
    _globals["_SHIPPINGORDERREPLY"]._serialized_end = 276
    _globals["_SHIPPINGORDER"]._serialized_start = 278
    _globals["_SHIPPINGORDER"]._serialized_end = 405
    _globals["_FINDSHIPPINGREQUEST"]._serialized_start = 407
    _globals["_FINDSHIPPINGREQUEST"]._serialized_end = 449
    _globals["_FINDSHIPPINGREPLY"]._serialized_start = 451
    _globals["_FINDSHIPPINGREPLY"]._serialized_end = 560
    _globals["_GETALLSHIPPINGREQUEST"]._serialized_start = 562
    _globals["_GETALLSHIPPINGREQUEST"]._serialized_end = 585
    _globals["_GETALLSHIPPINGREPLY"]._serialized_start = 587
    _globals["_GETALLSHIPPINGREPLY"]._serialized_end = 675
    _globals["_SHIPPINGSERVICE"]._serialized_start = 678
    _globals["_SHIPPINGSERVICE"]._serialized_end = 947
# @@protoc_insertion_point(module_scope)
